---
title: Processing Combined Data: GSE123813
author: 
- name: Nick Borcherding
  email: ncborch@gmail.com
  affiliation: Washington University in St. Louis, School of Medicine, St. Louis, MO, USA
date: "March 3rd, 2022"
output:
  BiocStyle::html_document:
    toc_float: true

---

```{r}
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(scDblFinder))
suppressPackageStartupMessages(library(BiocParallel))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(SingleR))
suppressPackageStartupMessages(library(celldex))
suppressPackageStartupMessages(library(scRepertoire))
suppressPackageStartupMessages(library(Azimuth))
suppressPackageStartupMessages(library(SeuratData))
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(stringr))
```


# Getting Processed Sequencing Runs

```{r}
HPCA <- HumanPrimaryCellAtlasData()
Monaco <- MonacoImmuneData()

dat <- readRDS("GSE123814.rds")
list <- SplitObject(dat, split.by = "orig.ident")

for (i in seq_along(list)){
    tmp <- UpdateSeuratObject(list[[i]])
    tmp <- subset(tmp, subset = nFeature_RNA > 100) #filter out low count/feature cells\
    
    orig.ident <- names(list)[i]
    orig.ident <- paste0(substring(orig.ident, 1,2), ".", substring(orig.ident, 3,3), ".", substring(orig.ident, 4, nchar(orig.ident)))
    
    barcodes <- paste0(orig.ident, "_", str_split(rownames(tmp[[]]), "_", simplify = TRUE)[,2])
    tmp <- RenameCells(tmp, new.names = barcodes)
    tmp$barcode <- rownames(tmp[[]])

    tmp[["mito.genes"]] <- PercentageFeatureSet(tmp, pattern = "^MT-")
    tmp[["ribo.genes"]] <- PercentageFeatureSet(tmp, pattern = "^RPS|RPL-")
    
     VlnPlot(object = tmp, 
            features = c("nCount_RNA", "nFeature_RNA", "mito.genes", "ribo.genes"), 
            pt.size = 0) + 
      theme(legend.position = "none") + 
      plot_layout(ncol =2)
      
    ggsave(paste0("~/Documents/GitHub/utility/qc/", orig.ident, ".pdf"), height = 8, width=8)
    
    ###########################
    #Here is the filtering step
    ############################
    ###### Already been filtered ########
    #standev <- sd(log(tmp$nFeature_RNA))*2.5 #cutting off above standard deviation of 2.5
    #mean <- mean(log(tmp$nFeature_RNA))
    #cut <- round(exp(standev+mean))
    #tmp <- subset(tmp, subset = mito.genes < 10 & nFeature_RNA < cut)
    
    ###########################################
    #Estimate Doublets for Each Sequencing Run
    ############################################
    sce <- as.SingleCellExperiment(tmp)
    sce <- scDblFinder(sce, BPPARAM=MulticoreParam(3))
    doublets <- data.frame(db.class = sce$scDblFinder.class, db.score = sce$scDblFinder.score)
    rownames(doublets) <- rownames(sce@colData)
    tmp <- AddMetaData(tmp, doublets)

    
    ###########################################
    #Estimate Doublets for Each Sequencing Run
    ############################################
    sce <- as.SingleCellExperiment(tmp)
    sce <- scDblFinder(sce)
    doublets <- data.frame(db.class = sce$scDblFinder.class, db.score = sce$scDblFinder.score)
    rownames(doublets) <- rownames(sce@colData)
    tmp <- AddMetaData(tmp, doublets)

    
   if(orig.ident %in% c("SC.T.3.1", "BC.T.1.2", "BC.T.2.3")) {
     tmp$predicted.celltype.l1.score <- NA
     tmp$predicted.celltype.l1 <- NA 
     tmp$predicted.celltype.l2.score <- NA
     tmp$predicted.celltype.l2 <- NA
     tmp$predicted.celltype.l3.score <- NA
     tmp$predicted.celltype.l3 <- NA
     tmp$mapping.score <- NA
   } else {
    ###########################################
    #Seurat Azimuth Annotation
    ############################################
    tmp <- NormalizeData(tmp, verbose = FALSE)
    tmp <- ScaleData(tmp, verbose = FALSE)
    VariableFeatures(tmp) <- getTopHVGs(as.SingleCellExperiment(tmp), 
                                        n=2000)
    tmp <- RunPCA(tmp, verbose = FALSE)
    tmp<- RunUMAP(tmp, dims = 1:30, verbose = FALSE)
    tmp <- FindNeighbors(object = tmp, 
                         features = VariableFeatures(tmp), 
                         verbose = FALSE)
    tmp <- RunAzimuth(tmp, 
                      reference = "pbmcref",
                      verbose = FALSE)
   }
      
    #############################################
    #Singler Annotation of Cell Types
    #############################################
      
    com.res1 <- SingleR(sce, ref=HPCA, labels=HPCA$label.fine, assay.type.test=1)
    df <- data.frame("labels" = com.res1$labels, "pruned.labels" = com.res1$pruned.labels)
    rownames(df) <- rownames(com.res1)
    colnames(df) <- paste0("HPCA.", colnames(df))
    tmp <- AddMetaData(tmp,  df)
  
    
    com.res2 <- SingleR(sce, ref=Monaco, labels=Monaco$label.fine, assay.type.test=1)
    df <- data.frame("labels" = com.res2$labels, "pruned.labels" = com.res2$pruned.labels)
    rownames(df) <- rownames(com.res1)
    colnames(df) <- paste0("Monaco.", colnames(df))
    tmp <- AddMetaData(tmp,  df)
    rm(df)
    rm(sce)
    
   processed.data <- tmp@meta.data[which(!is.na(tmp$CTaa)),] %>%
                        group_by(CTaa) %>%
                        mutate(clonalFrequency = n()) %>%
                        ungroup() %>%
                        mutate(clonalProportion = clonalFrequency / sum(clonalFrequency)) %>%
                        as.data.frame()
   
   if(nrow(processed.data) > 0) {
     rownames(processed.data) <- processed.data$barcode
     
     cloneSize=c(None = 0, Rare = 1e-4, Small = 0.001, 
               Medium = 0.01, Large = 0.1, Hyperexpanded = 1)
  
  
      processed.data$cloneSize <- NA
      
      for (x in seq_along(cloneSize)) { names(cloneSize)[x] <- 
                paste0(names(cloneSize[x]), ' (', cloneSize[x-1], ' < X <= ', cloneSize[x], ')') 
      }
  
  
  
      for (y in 2:length(cloneSize)) { 
        processed.data$cloneSize <- ifelse(processed.data$clonalProportion > cloneSize[y-1] & processed.data$clonalProportion <= cloneSize[y], names(cloneSize[y]), processed.data$cloneSize) 
      }
  
        processed.data <- processed.data[,c("CTgene", "CTnt", "CTaa", "CTstrict", "clonalFrequency", "clonalProportion", "cloneSize")]
        tmp <- AddMetaData(tmp, processed.data)
   } else {
     tmp$CTgene <- NA
     tmp$CTaa <- NA
     tmp$CTnt <- NA
     tmp$CTstrict <- NA
     tmp$clonalFrequency <- NA
     tmp$clonalProportion <- NA
     tmp$cloneSize <- NA
   }
      
      
      tmp@meta.data <- tmp[[]][,c("orig.ident", "nCount_RNA", "nFeature_RNA", "mito.genes", "ribo.genes", "CTgene",  "CTnt", "CTaa", "CTstrict",  "clonalFrequency", "clonalProportion", "cloneSize", "db.class", "db.score", "predicted.celltype.l1.score", "predicted.celltype.l1", "predicted.celltype.l2.score", "predicted.celltype.l2", "predicted.celltype.l3.score", "predicted.celltype.l3", "mapping.score", "HPCA.labels", "HPCA.pruned.labels", "Monaco.labels", "Monaco.pruned.labels")]
  
      tmp <- DietSeurat(tmp)
      tmp[["prediction.score.celltype.l1"]] <- NULL
      tmp[["prediction.score.celltype.l2"]] <- NULL
      tmp[["prediction.score.celltype.l3"]] <- NULL
      tmp[["query_ref.nn"]] <- NULL
      tmp@assays$RNA$scale.data <- NULL
    
    
      saveRDS(tmp, paste0("~/Documents/GitHub/utility/data/processedData/seuratObjects/", orig.ident, ".rds"))
      rm(tmp)
      gc()
}
```

