---
title: "rds to H5ad conversion"
author: 
- name: Nick Borcherding
  email: ncborch@gmail.com
  affiliation: Washington University in St. Louis, School of Medicine, St. Louis, MO, USA
date: "July 15, 2022"
output:
  BiocStyle::html_document:
    toc_float: true
---

```{r, echo=FALSE, results="hide", message=FALSE}
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
library(BiocStyle)
```

# Converting Formats

Per requests from users, the individual sequencing run output will be converted from .rds to .h5ad to facilitate working on the data in python. 

```{r}
library(reticulate)
library(SeuratDisk)
use_condaenv("r-reticulate")
files <- list.files("./data/processedData/individualSeurat/rds")
names <- stringr::str_remove_all(files, ".rds")

h5.files <- list.files("./data/processedData/individualSeurat/h5ad")
names.h5 <- stringr::str_remove_all(h5.files, ".h5ad")
files <- files[-which(names %in% names.h5)]
names <- stringr::str_remove_all(files, ".rds")

for(i in seq_along(files)) {
  tmp <- readRDS(paste0("./data/processedData/individualSeurat/rds/", files[i]))
  SaveH5Seurat(tmp, filename = paste0("./data/processedData/individualSeurat/h5ad/", names[i], ".h5Seurat"))
  Convert(paste0("./data/processedData/individualSeurat/h5ad/", names[i], ".h5Seurat"), dest = "h5ad")
  file.remove(paste0("./data/processedData/individualSeurat/h5ad/", names[i], ".h5Seurat"))
}
```

