---
title: Processing Combined Data: GSE179994
author: 
- name: Nick Borcherding
  email: ncborch@gmail.com
  affiliation: Washington University in St. Louis, School of Medicine, St. Louis, MO, USA
date: "March 3rd, 2022"
output:
  BiocStyle::html_document:
    toc_float: true

---

```{r, echo=FALSE, results="hide", message=FALSE}
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
library(BiocStyle)
```

#TCR Parsing

```{r}
library(dplyr)
dat <- read.table(gzfile("GSE179994_all.scTCR.tsv.gz"), header = TRUE)
meta <- read.table(gzfile("GSE179994_Tcell.metadata.tsv.gz"), header = TRUE)

CTnt <- paste0(dat$CDR3_nt.Alpha1., "_", dat$CDR3_nt.Beta1.)
CTaa <- paste0(dat$CDR3.Alpha1., "_", dat$CDR3.Beta1.)
CTgene <- paste0(dat$V_gene.Alpha1., ".", dat$J_gene.Alpha1., ".", NA, "_",
                 dat$V_gene.Beta1., ".", NA, ".", dat$J_gene.Beta1., ".", NA)
CTstrict <- paste0(dat$V_gene.Alpha1., ".", dat$J_gene.Alpha1., ".", NA, "_", dat$CDR3_nt.Alpha1., "_",
                   dat$V_gene.Beta1., ".", NA, ".", dat$J_gene.Beta1., ".", NA, "_", dat$CDR3_nt.Beta1.)

names <- data.frame(stringr::str_split(dat$CellName, "[.]", simplify = TRUE)[,1:3])
names$X3 <- ifelse(nchar(names$X3) > 1, NA, names$X3)
names$X2 <- ifelse(!is.na(names$X3), paste0(names$X2, ".", names$X3), names$X2)


sample <- names[,1]
ID <- names[,2]

processed.data <- data.frame(CTgene, CTnt, CTaa, CTstrict, sample = sample, ID =ID)
processed.data$barcode <- dat$CellName


processed.data <- processed.data %>%
    group_by(sample, CTnt) %>%
    mutate(Frequency = n()) %>%
    as.data.frame()



processed.data <- na.omit(processed.data)
rownames(processed.data) <- processed.data$barcode

nsize <- table(processed.data$sample)
uniq.patients <- unique(processed.data$sample)

for(i in seq_along(uniq.patients)) {
    processed.data[processed.data$sample == uniq.patients[i],"Frequency"] <- processed.data[processed.data$sample == uniq.patients[i],"Frequency"]/nsize[i]
}

cloneTypes=c(None = 0, Rare = 1e-4, Small = 0.001, 
             Medium = 0.01, Large = 0.1, Hyperexpanded = 1)


processed.data$cloneType <- NA
for (x in seq_along(cloneTypes)) { names(cloneTypes)[x] <- 
    paste0(names(cloneTypes[x]), ' (', cloneTypes[x-1], 
           ' < X <= ', cloneTypes[x], ')') }



for (i in 2:length(cloneTypes)) { processed.data$cloneType <- 
    ifelse(processed.data$Frequency > cloneTypes[i-1] & processed.data$Frequency 
           <= cloneTypes[i], names(cloneTypes[i]), processed.data$cloneType) }

saveRDS(processed.data, "ProcessedTCR_forutility.rds")
```


#RNA processing 

```{r}
library(Seurat)
RNA.dat <- readRDS(gzfile("GSE179994_all.Tcell.rawCounts.rds.gz"))
RNA.dat <-  CreateSeuratObject(RNA.dat)

names <- data.frame(stringr::str_split(rownames(RNA.dat[[]]), "[.]", simplify = TRUE)[,1:3])
names$X3 <- ifelse(nchar(names$X3) > 1, NA, names$X3)
names$X2 <- ifelse(!is.na(names$X3), paste0(names$X2, ".", names$X3), names$X2)
names$run <- paste0(names$X1, names$X2)

RNA.dat$orig.ident <- names$run

RNA.dat <- AddMetaData(RNA.dat, processed.data)

saveRDS(RNA.dat, "ProcessedRNA_forutility.rds")
```

#Utility Workflow and Export

```{r}
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(scDblFinder))
suppressPackageStartupMessages(library(BiocParallel))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ProjecTILs))
suppressPackageStartupMessages(library(scGate))
suppressPackageStartupMessages(library(Matrix))
suppressPackageStartupMessages(library(SingleR))
suppressPackageStartupMessages(library(celldex))
suppressPackageStartupMessages(library(scRepertoire))
```


```{r}
PT.ref <- load.reference.map("~/Documents/GitHub/utility/annotation/ref_TILAtlas_mouse_v1.rds")
HPCA <- HumanPrimaryCellAtlasData()
Monaco <- MonacoImmuneData()
scGate_models_DB <- get_scGateDB()


RNA.dat <- readRDS("ProcessedRNA_forutility.rds")
directory <- readxl::read_xlsx("~/Documents/GitHub/utility/summaryInfo/sample.directory.xlsx") #Meta.data
directory <- directory[directory$Cohort == "GSE179994",]

utility.sample.id <- directory$SampleLabel


list <- SplitObject(RNA.dat, split.by = "orig.ident")

list <- NULL
for (i in seq_along(list)){
    tmp <- list[[i]]

    tmp <- subset(tmp, subset = nFeature_RNA > 100) #filter out low count/feature cells\
    new.barcodes <- rownames(tmp@meta.data)
    new.barcodes <- stringr::str_sub(new.barcodes, nchar(new.barcodes)-17, nchar(new.barcodes))
    
    tmp  <- RenameCells(object = tmp , new.names = paste0(utility.sample.id[i], "_", new.barcodes))

    tmp[["mito.genes"]] <- PercentageFeatureSet(tmp, pattern = "^MT-")
    
    p1 <- VlnPlot(object = tmp, features = c("nCount_RNA")) + theme(legend.position = "none")
    p2 <- VlnPlot(object = tmp, features = c("nFeature_RNA")) + theme(legend.position = "none")
    p3 <- VlnPlot(object = tmp, features = c("mito.genes")) + theme(legend.position = "none")
    
    pdf(paste0("~/Documents/GitHub/utility/qc/", utility.sample.id[i], ".pdf"), height = 8, width=12)
    grid.arrange(p1, p2, p3, ncol = 3)
    dev.off()
    
    ###########################
    #Here is the filtering step
    ############################
    standev <- sd(log(tmp$nFeature_RNA))*2.5 #cutting off above standard deviation of 2.5
    mean <- mean(log(tmp$nFeature_RNA))
    cut <- round(exp(standev+mean))
    tmp <- subset(tmp, subset = mito.genes < 10 & nFeature_RNA < cut)
    
    ###########################################
    #Estimate Doublets for Each Sequencing Run
    ############################################
    sce <- as.SingleCellExperiment(tmp)
    sce <- scDblFinder(sce, BPPARAM=MulticoreParam(3))
    doublets <- data.frame(db.class = sce$scDblFinder.class, db.score = sce$scDblFinder.score)
    rownames(doublets) <- rownames(sce@colData)
    tmp <- AddMetaData(tmp, doublets)
    rm(sce)
    
    #############################################
    #Projectil Annotation of Cell Types
    #############################################
    
      query.projected <- make.projection(tmp, 
                                         ref = PT.ref, 
                                         scGate_model = scGate_models_DB$human$generic$Tcell.alphabeta,
                                         ncores = 1)
      
      #Lapply across list of Seurat objects
      query.projected <- cellstate.predict(ref = PT.ref, query =query.projected , reduction = "umap", ndim = 2)
        meta <- query.projected[[]][c("functional.cluster", "functional.cluster.conf")]
        colnames(meta) <- c("PT.annot", "PT.score")
        rownames(meta) <- stringr::str_remove(rownames(meta), "Q_")
      tmp <- AddMetaData(tmp, meta)
      rm(query.projected)
      
    #############################################
    #Singler Annotation of Cell Types
    #############################################
      
    tmp.2 <- tmp@assays[["RNA"]]@counts
    ####This approach for matrix conversion saves some memory
    tmp.2 <- tmp.2[tabulate(summary(tmp.2)$i) != 0, , drop = FALSE]
    com.res1 <- SingleR(tmp.2, ref=HPCA, labels=HPCA$label.fine, assay.type.test=1)
  
    df <- data.frame("labels" = com.res1$labels, "pruned.labels" = com.res1$pruned.labels)
    rownames(df) <- rownames(com.res1)
    colnames(df) <- paste0("HPCA.", colnames(df))
    tmp <- AddMetaData(tmp,  df)
  
    
    com.res2 <- SingleR(tmp.2, ref=Monaco, labels=Monaco$label.fine, assay.type.test=1)
    df <- data.frame("labels" = com.res2$labels, "pruned.labels" = com.res2$pruned.labels)
    rownames(df) <- rownames(com.res1)
    colnames(df) <- paste0("Monaco.", colnames(df))
    tmp <- AddMetaData(tmp,  df)
    rm(tmp.2)
    rm(df)
      
    saveRDS(tmp, paste0("~/Documents/GitHub/utility/data/processedData/individualSeurat/", utility.sample.id[i], ".rds"))
    
    #################################
    #Filter and Save Just T-AB cells
    #################################
    tmp$T.filter <- ifelse(!is.na(tmp$PT.annot) & !is.na(tmp$CTaa), "Tcell", "Non")
    if (length(which(tmp$T.filter == "Tcell")) > 1) {
        tmp <- subset(tmp, T.filter == "Tcell")
        saveRDS(tmp, paste0("~/Documents/GitHub/utility/data/processedData/individualTcells/", utility.sample.id[i], ".rds"))
        
        #################################
        #Save Just TCRs
        #################################
        
        TCR <- tmp[[]][,c("barcode", "CTgene", "CTaa")]
        rownames(TCR) <- NULL
        saveRDS(TCR, paste0("~/Documents/GitHub/utility/data/processedData/TCRs/", utility.sample.id[i], ".rds"))
        }
}
```

